#!/usr/bin/with-contenv bash

# First, let's make sure that all of our directories exist:
CONFIGDIRS="etc
            logs
            players
            plugins
            resource_packs
            worlds"

# Note: this will symlink etc and logs to /pocketmine, and we will never
# use them. Will leave it as is for now in order to keep the code simple.
for dir in $CONFIGDIRS; do
    if [ ! -d /config/${dir} ] && [ ! -e /config/${dir} ]; then
        mkdir -p /config/${dir}
        ln -s /config/${dir} /pocketmine/${dir}
    fi
done

# Now symlink the config files
CONFIGFILES="banned-ips.txt
             banned-players.txt
             ops.txt
             white-list.txt"

for file in $CONFIGFILES; do
    if [ ! -e /config/etc/${file} ]; then
        touch /config/etc/${file}
        ln -s /config/etc/${file} /pocketmine/${file}
    fi
done

# Finally, symlink the log files
if [ ! -e /config/logs/server.log ]; then
    touch /config/logs/server.log
    ln -s /config/logs/server.log /pocketmine/server.log
fi

# Handle the main configuration file separately since it exists in /pocketmine
if [ -e /pocketmine/server.properties ] && [ ! -L /pocketmine/server.properties ]; then
    mv /pocketmine/server.properties /config/etc/server.properties
    ln -s /config/etc/server.properties /pocketmine/server.properties
fi

# The yaml configuration file also needs special care, because the server will
# fail to start if it exists but is empty.
if [ ! -L /pocketmine/pocketmine.yml ]; then
    if [ -e /pocketmine/pocketmine.yml ] && [ ! -e /config/etc/pocketmine.yml ]; then
        mv /pocketmine/pocketmine.yml /config/etc/pocketmine.yml \
        && ln -s /config/etc/pocketmine.yml /pocketmine/pocketmine.yml
    elif [ ! -e /pocketmine/pocketmine.yml ] && [ -e /config/etc/pocketmine.yml ]; then
        ln -s /config/etc/pocketmine.yml /pocketmine/pocketmine.yml
    fi
fi

# permissions
chown -R minecraft:minecraft \
        /config \
        /pocketmine

# Configure PHP
PHP_INI=/usr/local/etc/php/php.ini
TIMEZONE=$(date +%Z)
if [ ! -e ${PHP_INI} ]; then
    echo "date.timezone=$TIMEZONE" > "${PHP_INI}"
    echo "short_open_tag=0" >> "${PHP_INI}"
    echo "asp_tags=0" >> "${PHP_INI}"
    echo "phar.readonly=0" >> "${PHP_INI}"
    echo "phar.require_hash=1" >> "${PHP_INI}"
    echo "igbinary.compact_strings=0" >> "${PHP_INI}"
    echo "zend.assertions=-1" >> "${PHP_INI}"
    echo "error_reporting=-1" >> "${PHP_INI}"
    echo "display_errors=1" >> "${PHP_INI}"
    echo "display_startup_errors=1" >> "${PHP_INI}"
    echo ";zend_extension=opcache.so" >> "${PHP_INI}"
    echo "opcache.enable=1" >> "${PHP_INI}"
    echo "opcache.enable_cli=1" >> "${PHP_INI}"
    echo "opcache.save_comments=1" >> "${PHP_INI}"
    echo "opcache.fast_shutdown=0" >> "${PHP_INI}"
    echo "opcache.max_accelerated_files=4096" >> "${PHP_INI}"
    echo "opcache.interned_strings_buffer=8" >> "${PHP_INI}"
    echo "opcache.memory_consumption=128" >> "${PHP_INI}"
    echo "opcache.optimization_level=0xffffffff" >> "${PHP_INI}"
fi