#!/usr/bin/with-contenv bash

PLUGINS=${PLUGINS:-https://poggit.pmmp.io/r/42013/PureEntitiesX.phar}

echo "**** Installing Plugins ****"
for plugin in ${PLUGINS}; do
    plugin_name=`echo "${plugin##*/}"`
    if [ ! -e /config/plugins/${plugin_name} ]; then
        echo "[ ] installing ${plugin_name}..."
        wget ${plugin} -O /config/plugins/${plugin_name}
    else
        echo "[X] ${plugin_name} is already installed."
    fi
done
